### ISSUE TITLE
Autodetection/Oculus/Non-VR crashes DCS when using some reshade packs

### ISSUE THREAD

**Issue by franukis** [fredemmott/OpenKneeboard#42] opened 2022-03-21 07:18 UTC
Just as per the title, DCS closes itself when launching Openkneeboard in latest release. My config:

- HP Reverb G2
- SteamVR launched via WMR for SteamVR
- DCS OpenBeta latest 
- DCS hooks not installed
- Wacom (Intuos S) tablet connected, recognized and 1 button binded (just testing so far)
- Json file attached (could not find anything else, like a log. Checked also "(...)\AppData\Local\Packages\FredEmmott.Self.OpenKneeboard_.....)

After it happens, closing the app will not kill the process, preventing DCS fromstarting again, so I have to manually close the OpenKneeboard process
[Settings.zip](https://github.com/fredemmott/OpenKneeboard/files/8313636/Settings.zip)

**Comment by fredemmott** [comment] 2022-03-21 13:07
Can you share the DCS log and crash dump? As it’s DCS crashing, those are needed, even if it’s OpenKneeboard causing it

**Comment by fredemmott** [comment] 2022-03-21 13:15
It will also log some information to the system debug stream - https://docs.microsoft.com/en-us/sysinternals/downloads/debugview#introduction is the best way to view it

**Comment by fredemmott** [comment] 2022-03-21 14:23
As for what's going on, without the hooks, OpenKneeboard does 3 things to DCS:

1. loads a DLL that talks to the wacom/huion driver. There is no way for OpenKneeboard to 'own' the tablet when it's not the active window, so, it makes DCS own it and forward penstrokes/buttonpresses.
2 loads a different DLL that detects if steamvr, oculus SDK, or non-VR rendering is being used
3. (shouldn't be happening for you) If oculus SDK or non-VR rendering is being used, it then modifies directX or the oculus SDK in memory to also render the kneeboard.

2. is where the problem is. There's no proper way to do any of this - part of DirectX needs to be rewritten in memory to figure out what DCS is doing. Whatever software is incompatible isn't 'buggy', nor is OpenKneeboard here: any two applications doing this can interfere with each other, and they made need specific code to play nicely together.

For example, the steam and discord overlays work the same way, and both OpenKneeboard and Discord have special code to be compatible with the steam overlay.

**Comment by franukis** [comment] 2022-03-21 15:00
Thx for the detailed information. Ther could be two things...
- Discord running in background
- fpsVR app which launches automatically with steamVR and has the ability to inject another overlay... even though I think it was hidden

Let me re-run the test with both apps off, and I will come back :)

**Comment by fredemmott** [comment] 2022-03-21 15:05
> Discord

This is likely, I'll see if I can reproduce the problem

> fpsVR

While this has /some/ oculus support, I'd expect it to just be running in steamvr mode for you and not be a problem.

---

While I'd like to fix (or at least identify) whatever's interacting with the autodetection, I'm also going to add an option to force steamvr and skip the autodetection, which should be a workaround.

**Comment by fredemmott** [comment] 2022-03-21 16:35
From the crash dump:

`C:\Program Files\Eagle Dynamics\DCS World OpenBeta\bin\dxgi.dll`

This interacts with the DirectX implementation, and isn't a normal part of DCS or Microsoft's version from system32 (it has no author data); do you know where it came from? Removing it may resolve the issue

`C:\Users\franu\Saved Games\DCS.openbeta\Mods\Services\DCS-SRS\bin\srs.dll`

Ok, I know this one, but don't use it :) Is there anything visible in DCS when using it?

**Comment by Sirtz** [comment] 2022-03-21 18:35
Having crashes as well, anything that could draw on top of DCS is: Simple Radio, Scratchpad mod. I think that's it?

**Comment by franukis** [comment] 2022-03-21 19:51
I will have a look into dxgi.dll as I don‘t recall what it is …

SRS does indeed show some info, but it is integrated into DCS as if it was a module. There‘s a key combo to show a window/dialog with the connection status and the channels/frequencies. But I inow people using it together with Openkneeboard with no issues, so I will explore the first lead first ;)

**Comment by fredemmott** [comment] 2022-03-22 00:21
[OpenKneeboard-RelWithDebInfo.msix](https://github.com/fredemmott/OpenKneeboard/suites/5746116943/artifacts/190664278) from https://github.com/fredemmott/OpenKneeboard/actions/runs/2019411271 may fix this; if it doesn't, it also adds an API choice to the game settings. If you set that to SteamVR it should work around this.

Any chance you're using RivaTuner or MSI Afterburner?

**Comment by franukis** [comment] 2022-03-22 07:14
I will give it a try: uninstall current version, and install using that .msix

Regarding Afterburner, I have it somewhere (as well as the equivalent ASUS GPU Tweak II), but it was not running, and it is not installed, so the process was not running in background... will double check, just in case, though.

**Comment by franukis** [comment] 2022-03-22 07:26
> Please let me know if it works on auto-detect, and if not, if steamvr fixes it.

Auto-detect did not work, but manually setting to SteamVR did work perfectly :)

**Comment by fredemmott** [comment] 2022-03-22 13:19
If you’re interested in continuing to figure out what the interaction is in auto detect mode, please leave this open; if you’d rather just get on with using it now there’s a workaround, please close it.

once closed, I’ll lock this issue: there’s a tendency for other people to report new issues by commenting on issues like this one - even if closed - instead of opening new ones which makes it hard to keep track of what discussions are relevant to each problem

**Comment by franukis** [comment] 2022-03-22 14:00
It is fine for me to work with no auto-detect. However, if you want to investigate why it did not work, I am available to support and run the tests you want.

I will close the issue now and, if you want to continue the investigation, just re-open/ping me, and I will support to the best of my knowledge :) (I mean, I have my own SW development - shameless plug: DCS Datcard Generator-, and sometimes I feel more offended by a bug, cause I do not understand it, than the users, who are happy with a workaround)

**Comment by fredemmott** [comment] 2022-03-22 14:27
Were you able to try removing dxgi.dll from the DCS bin folder? Other than that, the only clear next step would be to go through task manager and kill *everything* related to performance monitoring or gaming

**Comment by franukis** [comment] 2022-03-22 15:00
Honestly, I had forgotten about it... However, just looked into the folder and looking into a dxgi.log, I learnt it was related to Reshade (I had a user mod called "VR Sharpen color IGM" that was a pre-configured Reshade). I disabled it via Ovgme, and confirmed that dxgi.dll was no longer present in bin folder... and now Auto-detect works!!!

**Comment by fredemmott** [comment] 2022-03-22 15:10
Thanks :)

**Comment by fredemmott** [comment] 2022-03-22 15:10
For now, this is "explicitly use steamvr or don't use reshade", but should be possible to make them play nicely together.

**Comment by fredemmott** [comment] 2022-03-23 00:34
So, brief experimentation:
- latest reshade with defaults installed is fine
- latest vrperfkit is fine

Given OpenKneeboard doesn't care about the specific shaders used, I'm guessing this was an old version of reshade with an older dxgi.dll ; both vrperfkit and latest reshade replace dxgidll with one that doesn't interfere with openkneeboard

**Closed by fredemmott** 2022-03-23 00:34 UTC
