### ISSUE TITLE
Performance Problems with all steamvr overlays with HP reverb G2

### ISSUE THREAD

**Issue by Sirtz** [fredemmott/OpenKneeboard#21] opened 2022-01-30 13:24 UTC
I am having performance issues using OpenKneeboard, but also using VR Kneeboard. I tried the latest build from the GitHub action. Tested F/A-18 "airfield defense" instant action on Syria to put some strain on my PC. Mods On/Off does not make a difference.

Without openkneeboard: around 35 fps, but pretty smooth picture. 
With openkneeboard: 29 fps, laggy picture, seeing double vision. 
My GPU is at over 95% utilization with the kneeboard on or off, doesn't change much. 

Settings:
![](https://cdn.discordapp.com/attachments/807359995557183530/937331991689433108/unknown.png)

![](https://cdn.discordapp.com/attachments/807359995557183530/937332067522461696/unknown.png)

![](https://cdn.discordapp.com/attachments/807359995557183530/937332183482368020/unknown.png)

![](https://cdn.discordapp.com/attachments/807359995557183530/937332839714816030/unknown.png)

Specs:
Ryzen 5 5600X
RTX 3070
32GB Ram @3000
Up to date Win10, fresh install
DCS and OS on NVME SSD
Reverb G2 (Windows Mixed reality -> SteamVR -> DCS)

**Comment by fredemmott** [comment] 2022-01-30 13:43
Retitled based on discord discussion - in particular that this isn’t specific to openkneeboard.

**Comment by fredemmott** [comment] 2022-01-30 16:58
This is fine for me with steamvr with a 3090ti and Oculus Quest; most obvious differences are:
- GPU memory - and 3070 (8gb) vs 3090 (24gb) more generally
- Oculus vs WMR+HP drivers

Things to check performance of:
- [ ] handling gaze zoom
   - [ ] fetching position
   - [ ] built-in "is headset pointing at this overlay" function
- [ ] SetOverlayWidthInMeters, even when no change
- [ ] polling for overlay events
- [ ] texture
  - [ ] BGRA vs RGBA textures (BGRA is needed for other systems, e.g. Direct2D, but conversion can be done outside of OpenVR if needed)
  - [ ] alpha (translucency); already done in the most efficient way, may need to be disabled or optional
 - [ ] SetOverlayTransformAbsolute, even if no change (unlikely: only done when page/tab changes)
 - [ ] GPU RAM
 - [ ] some other issue in SteamVR/WMR/HP drivers
 - [ ] some other issue in OpenKneeboard

**Comment by fredemmott** [comment] 2022-01-30 17:54
>  SetOverlayWidthInMeters, even when no change

If that last commit (and corresponding build, click on the colored dot when it's green if you're not building yourself) fixes it, this was the problem, otherwise it's ruled out

>  handling gaze zoom

If commenting out the lines I mentioned in discord fixes it, it's one of these subproblems, otherwise it's ruled out

**Comment by fredemmott** [comment] 2022-01-30 19:09
Ticked options are addressed in latest build, don't know if they're the cause though.

**Comment by Sirtz** [comment] 2022-01-30 19:35
> Ticked options are addressed in latest build, don't know if they're the cause though.

So with the latest GitHub action build I can try again?

**Comment by fredemmott** [comment] 2022-01-30 19:37
Yes, but please separately try commenting out the gaze stuff (https://github.com/fredemmott/OpenKneeboard/blob/master/src/app/okOpenVRThread.cpp#L141-L180) if the latest version doesn't resolve it

**Comment by fredemmott** [comment] 2022-01-30 19:54
>  GPU RAM
>  some other issue in OpenKneeboard

I'm not able to get meaningful numbers for OpenKneeboard here - https://docs.microsoft.com/en-us/troubleshoot/windows-client/performance/gpu-process-memory-counters-report-wrong-value kicks in so they're nonsense. I can easily make it say I'm using 3TB of GPU memory.

**Comment by 000Ready000** [comment] 2022-02-01 21:48
Hi I am also using a G2 and am having similar degraded performance with VRK. Is there any way I can help to test?

**Comment by fredemmott** [comment] 2022-02-01 21:56
Are you able to build yourself? If not, try downloading the 'OpenKneeboard-RelWithDebInfo' version from https://github.com/fredemmott/OpenKneeboard/actions/runs/1779544249

If that works without issues for you, great, this might be fixed :)

If that doesn't fix the problem, you're comfortable building from source and already familiar with cmake + visual studio, the next step is seeing if commenting out https://github.com/fredemmott/OpenKneeboard/blob/master/src/app/okOpenVRThread.cpp#L141-L180 fixes it; if not https://github.com/fredemmott/OpenKneeboard/blob/master/src/app/okOpenVRThread.cpp#L130-L139

If neither, and you're familiar with direct2d or direct3d, try changing the texture format

If none of those, seems likely to be an unworkable issue with steamvr/winvr/HP drivers

**Comment by fredemmott** [comment] 2022-02-01 21:57
commenting those sections out removes functionality - the purpose of commenting them out isn't to fix it, just to identify which parts of the openvr API are slowing things down.

**Comment by 000Ready000** [comment] 2022-02-01 22:56
Hi sorry I forgot to say, I am not a programmer, just an enthusiastic DCS player. I am only able to put files in folders using OVGME and adjusting some basic configuration files in plain text.

**Comment by fredemmott** [comment] 2022-02-02 00:40
>  If not, try downloading the 'OpenKneeboard-RelWithDebInfo' version from https://github.com/fredemmott/OpenKneeboard/actions/runs/1779544249

You should see this in the artifacts section - it's a zip file; extract it, then in `bin/` you'll have `OpenKneeboard.exe` - try that :)

**Comment by fredemmott** [comment] 2022-02-17 02:01
Can anyone confirm whether or not this is still an issue?

**Comment by 000Ready000** [comment] 2022-02-17 07:25
When I return home in a week or so will give it a try. 

⁣BlueMail voor Android downloaden ​

Op 17 feb. 2022 04:02, om 04:02, Fred Emmott ***@***.***> schreef:

**Comment by Sirtz** [comment] 2022-02-20 18:56
I am not at home as well. Can only test in a week or so

**Comment by fredemmott** [comment] 2022-03-12 17:11
Closing: no reports of this in a long time, and several g2 users are happy

>  built-in "is headset pointing at this overlay" function

Coincidentally removes this in 64b56568d4db61a938518810dcbb6bc7c535835c as part of #39

**Closed by fredemmott** 2022-03-12 17:11 UTC
Labels: question

**Comment by fredemmott** [comment] 2022-04-07 13:51
Following up, problems resolved for  original reporter (@Sirtz ) by using OpenComposite + the openxr alpha instead of steamvr
